import 'package:flutter/material.dart';

Color appColor = const Color(0xFF41BA3E);
Color appColor2 = const Color(0xFF115010);
Color appColorBlue = const Color(0xFF262F64);
Color appColorVertJaune = const Color(0xFFB3C905);
Color appColorJaune = const Color(0xFFFFE000);
Color appBlack = const Color(0xFF000000);
Color appWhite = const Color(0xFFFFFFFF);
Color appDegradOne = const Color(0xFFEFFDEF);
Color appDegradTwo = const Color(0xFF2B5F29);
Color appIndicator = const Color(0xFFD2F4D1);
Color appTextIndicator = const Color(0xFFCCFFCB);
Color appFondLogin = const Color(0xFFE2F7E6);
Color appTextOne = const Color(0xFF666666);
Color appTextTwo = const Color(0xFF8A8A8F);
Color appTextTree = const Color(0xFFF4FFF4);
Color appColorRed = const Color(0xFFF80000);
Color appColorRedFond = const Color(0xFFFFEBEB);
Color appColorDivider = const Color(0xFFD8EBDC);
Color appColorContact = const Color(0xFFEFF4F8);
Color appColorOrange = const Color(0xFFF88600);
Color appColorOrangeText = const Color(0xFF9A5505);
Color appColorOrangeFond = const Color(0xFFFFFAF4);
Color appColorReserve = const Color(0xFF3E77BA);
Color appColorCard = const Color(0xFFFAFAFA);
Color appColorNavigation = const Color(0xFFD4D9D5);
Color appColorHtml = const Color(0xFF006699);
Color appColorPurple = const Color(0xFF9C27B0);


Color primaryGreen = Color(0xFF2E7D32);
Color lightGreen = Color(0xFF4CAF50);
Color accentGreen = Color(0xFF81C784);
Color backgroundGreen = Color(0xFFF1F8E9);
Color cardBackground = Colors.white;
Color textDark = Color(0xFF1B1B1B);
Color textGrey = Color(0xFF757575);
Color textLight = Color(0xFF9E9E9E);
Color borderColor = Color(0xFFE0E0E0);
Color warningYellow = Color(0xFFFFF9C4);
Color warningBorder = Color(0xFFF9A825);
Color errorRed = Color(0xFFD32F2F);
Color infoBlue = Color(0xFF1976D2);
Color infoBlueLight = Color(0xFFE3F2FD);